GPS_enable: false
GPS_path: /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTBI9WHN-if00-port0
IMU_addr: ''
IMU_enable: false
SuperSensor_enable: true
SuperSensor_path: /dev/serial/by-id/usb-FTDI_TTL232R-3V3_FTBI9WHN-if00-port0
